Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$syncScript = Join-Path $PSScriptRoot "Sync-NinjaCrawlerCargoLockVersion.ps1"
$fixtureRoot = Join-Path ([System.IO.Path]::GetTempPath()) ("cargo-lock-sync-" + [guid]::NewGuid())

function Write-FixtureFile {
    param(
        [Parameter(Mandatory)][string]$RelativePath,
        [Parameter(Mandatory)][string]$Content
    )
    $path = Join-Path $fixtureRoot $RelativePath
    $directory = Split-Path -Parent $path
    if ($directory) {
        New-Item -ItemType Directory -Path $directory -Force | Out-Null
    }
    $normalized = $Content -replace "`r`n", "`n"
    if (-not $normalized.EndsWith("`n")) {
        $normalized += "`n"
    }
    $utf8NoBom = New-Object System.Text.UTF8Encoding $false
    [System.IO.File]::WriteAllText($path, $normalized, $utf8NoBom)
}

try {
    New-Item -ItemType Directory -Path $fixtureRoot -Force | Out-Null

    Write-FixtureFile -RelativePath "src-tauri/Cargo.toml" -Content @'
[package]
name = "ninjacrawler"
version = "0.27.0" # x-release-please-version
edition = "2021"
'@

    Write-FixtureFile -RelativePath "src-tauri/Cargo.lock" -Content @'
# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "example"
version = "1.0.0"

[[package]]
name = "ninjacrawler"
version = "0.26.0" # x-release-please-version
dependencies = [
 "example",
]
'@

    $synced = & $syncScript -RepositoryRoot $fixtureRoot
    if ($synced -ne "0.27.0") {
        throw "Sync script should report the Cargo.toml version, got '$synced'."
    }

    $lockAfter = Get-Content -LiteralPath (Join-Path $fixtureRoot "src-tauri/Cargo.lock") -Raw
    if ($lockAfter -notmatch '(?ms)name\s*=\s*"ninjacrawler"\s*version\s*=\s*"0\.27\.0"\s') {
        throw "Sync script did not rewrite the ninjacrawler package version."
    }
    if ($lockAfter -match 'x-release-please-version') {
        throw "Sync script must strip the legacy Release Please marker from Cargo.lock."
    }
    if ($lockAfter -notmatch '(?ms)name\s*=\s*"example"\s*version\s*=\s*"1\.0\.0"') {
        throw "Sync script must not rewrite unrelated package versions."
    }

    $again = & $syncScript -RepositoryRoot $fixtureRoot
    if ($again -ne "0.27.0") {
        throw "Idempotent sync should still report the expected version."
    }

    & $syncScript -RepositoryRoot $fixtureRoot -Check | Out-Null

    Write-FixtureFile -RelativePath "src-tauri/Cargo.toml" -Content @'
[package]
name = "ninjacrawler"
version = "0.28.0" # x-release-please-version
edition = "2021"
'@

    $checkFailed = $false
    try {
        & $syncScript -RepositoryRoot $fixtureRoot -Check | Out-Null
    } catch {
        $checkFailed = $true
        if ("$_" -notmatch 'Sync-NinjaCrawlerCargoLockVersion') {
            throw "Check mode should point operators at the sync script. Error: $_"
        }
    }
    if (-not $checkFailed) {
        throw "Check mode must fail when Cargo.lock lags Cargo.toml."
    }

    Write-Output "Sync-NinjaCrawlerCargoLockVersion tests passed."
}
finally {
    if (Test-Path -LiteralPath $fixtureRoot) {
        Remove-Item -LiteralPath $fixtureRoot -Recurse -Force
    }
}
